### ISSUE TITLE
Can't compile the code.

### ISSUE THREAD

**Issue by rilindnuka** [t0mg/wordclock#1]
Great project, i like it a lot
I can't get it to compile though... I get the following when i try to compile the provided code. 
I am probably missing something and not seeing it.

`In file included from /Users/rilindnuka/Documents/personal/wordclock/software/wordclock/wordclock.ino:9:0:
/Users/rilindnuka/Documents/personal/wordclock/software/wordclock/src/Iot.h:64:3: error: 'IotWebConfParameter' does not name a type
   IotWebConfParameter ntp_enabled_param_;
   ^
/Users/rilindnuka/Documents/personal/wordclock/software/wordclock/src/Iot.h:69:3: error: 'IotWebConfParameter' does not name a type
   IotWebConfParameter timezone_param_;
   ^
/Users/rilindnuka/Documents/personal/wordclock/software/wordclock/src/Iot.h:74:3: error: 'IotWebConfParameter' does not name a type
   IotWebConfParameter manual_date_param_;
   ^
/Users/rilindnuka/Documents/personal/wordclock/software/wordclock/src/Iot.h:79:3: error: 'IotWebConfParameter' does not name a type
   IotWebConfParameter manual_time_param_;
   ^
/Users/rilindnuka/Documents/personal/wordclock/software/wordclock/src/Iot.h:84:3: error: 'IotWebConfParameter' does not name a type
   IotWebConfParameter show_ampm_param_;
   ^
/Users/rilindnuka/Documents/personal/wordclock/software/wordclock/src/Iot.h:89:3: error: 'IotWebConfParameter' does not name a type
   IotWebConfParameter ldr_sensitivity_param_;
   ^
/Users/rilindnuka/Documents/personal/wordclock/software/wordclock/src/Iot.h:94:3: error: 'IotWebConfParameter' does not name a type
   IotWebConfParameter color_param_;
   ^
/Users/rilindnuka/Documents/personal/wordclock/software/wordclock/src/Iot.h:99:3: error: 'IotWebConfSeparator' does not name a type
   IotWebConfSeparator time_separator_;
   ^
/Users/rilindnuka/Documents/personal/wordclock/software/wordclock/src/Iot.h:100:3: error: 'IotWebConfSeparator' does not name a type
   IotWebConfSeparator display_separator_;
   ^
exit status 1
Error compiling for board ESP32 Dev Module.`

**Comment by kvlavieren** [comment]
I have the same issue.

**Comment by t0mg** [comment]
Hello and thanks for your interest :)

IotWebConf had a major (breaking) update since I published this, you might need to use an older version (check the packages file). I need to rewrite the code to use the latest version but unfortunately I lack the time to do so at the moment :/

Let me know it that helps!

**Comment by t0mg** [comment]
I have now tagged a 1.0 release and attached a prebuilt binary https://github.com/t0mg/wordclock/releases

Some updates are coming to this project, including hopefully upgrading the iotwebconf library to a later release.

**Comment by t0mg** [comment]
iotwebconf is now updated to latest, closing this issue now :)
