### ISSUE TITLE
Network box

### ISSUE THREAD

**Issue by IlGiurgi** [t0mg/wordclock#24]
Is it possible  to hide the network box or to collapse it if the network is already set up? or at least place it at the bottom.

**Comment by t0mg** [comment]
Yes, good idea. I'll look into it.

**Comment by t0mg** [comment]
Thanks ! your Italian clock face was just added to the repository with PR #27 

Regarding updates not working, there was a timer bug that was just fixed yesterday that could have caused this, but if you are still able to reproduce it would be helpful to see if there's any info on the serial console.

As for AMPM it's the same with French actually (unused too), I need to think of a simple way to toggle that.

**Comment by IlGiurgi** [comment]
Can I reach out to you somehow? I have issues with the new code. If you can, text me at @ilgiurgi on telegram.

**Comment by t0mg** [comment]
Sorry I'm not in telegram. Feel free to file as many issues as necessary here! It might help others.

**Comment by IlGiurgi** [comment]
For some reason I messed up something maybe with the cables or something but the ESP keeps rebooting with the code, I tried uploading a code to see if each component works well and they do, so I can't figure out what's the reason of the reboots.. That's the error, I always used same usb cables ecc so it could be the board maybe?
12:51:36.869 -> 
12:51:36.869 -> Brownout detector was triggered
12:51:36.869 -> 
12:51:36.869 -> ets Jul 29 2019 12:21:46
12:51:36.869 -> 
12:51:36.869 -> rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
12:51:36.869 -> configsip: 0, SPIWP:0xee
12:51:36.869 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
12:51:36.869 -> mode:DIO, clock div:1
12:51:36.869 -> load:0x3fff0030,len:1344
12:51:36.869 -> load:0x40078000,len:13964
12:51:36.869 -> load:0x40080400,len:3600
12:51:36.869 -> entry 0x400805f0

**Comment by t0mg** [comment]
Uh oh `Brownout detector was triggered` ?

Is the power supply too weak?

**Comment by t0mg** [comment]
Ok thanks for the heads up I will also do some testing

**Comment by t0mg** [comment]
As of 1d2bcd9 there is now a language selector (including italian) and we hide the am/pm if unused. We also move the network section to the bottom after initial setup.

I've tested the firmware on my clock and it works without issue, so I'll close this ticket (which was about the network section of the web UI) but feel free to open another if your issues persist!
