### ISSUE TITLE
cannot connect 

### ISSUE THREAD

**Issue by winner69** [t0mg/wordclock#3]
Hi Tom, I finished upload  your code to ESP32, 
my mobile cannot find AP name "wordclock"

**Comment by t0mg** [comment]
Sorry about this @winner69. There could be many reasons to that symptom. I know it's been a while but if you're still interested, could you try building the project with debug enabled to see if anything useful comes up on the serial interface ? Please feel free to reopen the issue if you have more information. Thanks!
