### ISSUE TITLE
Display ip address at startup with led matrix

### ISSUE THREAD

**Issue by LePtitNicolas** [t0mg/wordclock#42]
Hi,

I am in the process of making a clock. I took your version with the "paint" functionality and the mqtt options because I think it opens up interesting perspectives!

I was thinking about a function to display scrolling text using the LEDs as a matrix.
It would thus be possible to display the IP address of the clock at startup, for example. It would be really very practical to know if it is in AP mode or if it is connected to the local network and in the latter case, to have the IP address to connect to it without having to plug in a USB cable to know it with the serial monitor or having to look for it on the box.
The function could also be used to display a scrolling message sent via an mqtt request. We could imagine programming messages on Home Assistant for events (happy birthday, merry Christmas, etc.)

But I admit that I am not comfortable enough with programming to implement this development...

**Comment by DaveDavenport** [comment]
Not sure if we can easily display every ip address on each faceplate. 

In  AP mode your browser should automatically redirect to the wordclock webpage.

Once connected to your wifi, I think the clock should be reachable via the wordclock.local hostname (with default settings).

**Comment by t0mg** [comment]
Local domain doesn't work with all routers, but it's definitely worth trying :) On the other hand, routers/boxes all provide a way to list connected devices so you should not need to use serial to discover the IP anyway.

A generic scrolling text / ticker feature over mqtt is a logical next step after paint mode. I just lack the time to work on that 😅

After that, showing the IP after connection would be doable. Generally speaking having some info during boot could be cool. It is rather niche though, as normally you'd only need that once. A generic text ticker however could be nice for home automation purposes.

**Comment by LePtitNicolas** [comment]
Thanks for taking the time to respond !

Indeed, the display of the IP address should only be used at startup, which should be rare, however, the generic scrolling text / ticker feature over mqtt will be a real plus :-p

**Comment by t0mg** [comment]
Generic text scroller feature is now available :)
https://github.com/t0mg/wordclock/blob/main/software/UsersManual.md#text-scroller

**Comment by t0mg** [comment]
Feature added in a83c5e8
