### ISSUE TITLE
Impossible to change Time

### ISSUE THREAD

**Issue by antoblasco** [t0mg/wordclock#45]
I Tom,

I’m trying to change the time manually but doesn’t work. The HMI said "configuration saved", but is not true. Could you help me please?

**Comment by t0mg** [comment]
Thanks @antoblasco. I can reproduce the issue. Looks like we broke manual time setting at some point (I'm always using NTP so I hadn't noticed before). Will have a look.

**Comment by antoblasco** [comment]
No because at the moment I don’t need it

**Comment by antoblasco** [comment]
I see that you close the issue without any new release, why @t0mg ?

at the moment I’m not able to change the code, I haven’t too much programming skill 😆🙈 for me will be better a new SW release via OTA

**Comment by DaveDavenport** [comment]
It is closed because its fixed in https://github.com/t0mg/wordclock/commit/b31e9b50376087dfdd1c8171b805425b68cc3940 .  This will be part of a next release.
A release is normally more then a single issue and consists of a collection of closed issues and new features.

**Comment by antoblasco** [comment]
Ok ok I didn’t know. No problem, I can wait. Thank you a lot really for your support. I’m new on GitHub and I don’t know all’ the procedure, sorry.

**Comment by t0mg** [comment]
I was about to publish a new release anyway:) 

I'm not sure this issue is really closed though if you didn't have MQTT enabled. But in that case I am not able to reproduce your problem on my wordclocks

**Comment by t0mg** [comment]
@antoblasco new release is available with this fix. You can update over wifi via the firmware update link in the config page using the provided ota.bin file, or flash via USB with the other bin file. But if you don't use mqtt your problem might be something else. Let us know.
