### ISSUE TITLE
Red color of startup animation doesn’t work properly

### ISSUE THREAD

**Issue by antoblasco** [t0mg/wordclock#47]
Hi all,

After trying to resolve the issue 46 by unplug and plug the power a couple of time also waiting more than 5 minutes between the unplug and plug, I’ve noticed that the color red during the startup animation, doesn’t turn ON a lot of leds.

At the beginning was everythink ok.

The strip led is not broken, infact the white color is working properly on all LEDs.

This issue can be related to the 46 or you think that there is an other problem?

thanks

**Comment by t0mg** [comment]
I've noticed it. Blocking operations at boot time prevent the animation from showing. Not a huge problem IMO but we could delay the boot animation to reduce this (which would make startup time longer).

**Comment by antoblasco** [comment]
Hi @t0mg , I think that is not necessary to startup the clock fastly, it’s just a clock. So I think that we could try to use your solution to resolve this issue, because the startup animation is also helpfull to understand if there’s a damaged led 😄

I’m really happy to debug the SW and help all of you to reach the best release 💪🏻
