### ISSUE TITLE
URL for Text Scroller API incorrect

### ISSUE THREAD

**Issue by Hjalmgunnarson** [t0mg/wordclock#49]
The [User Manual](https://github.com/t0mg/wordclock/blob/main/software/UsersManual.md#text-scroller) states that text can be set via the API using http://<clock IP>/api/text/set/example, but this yields

> Requested a non-existing page
> 
> URI: /api/text/set/example

file: software/wordclock/src/src/Iot.cpp line 364

/-  web_server_.on(UriBraces("/api/text/{}"), [this]() {
/+ web_server_.on(UriBraces("/api/text/set/{}"), [this]() {

**Comment by Hjalmgunnarson** [comment]
Awesome project by the way. Many thanks. My father and me both made a clock using the excellent instructions and had some great quality time doing so.

**Comment by t0mg** [comment]
Thanks for reporting the issue, and the nice words. Means a lot!
