### ISSUE TITLE
Crashes on ESP32C3

### ISSUE THREAD

**Issue by tjfsteele** [t0mg/wordclock#9]
Timer.cpp line 32 tries to create timer 3 but the ESP32C3 only has two. 

Suggest changing the line to 

`    timer_ = timerBegin(1, 8000, 1); // div 80
`

**Comment by t0mg** [comment]
Would you mind sending a PR? 

Note: I plan on updating this project with the new version of IOTWebConf but this got delayed by external factors (I broke my own clock). Any contribution towards maintaining this project is most welcome :)

Thanks!

**Comment by tjfsteele** [comment]
I've submitted a PR. Thank you for accepting the previous one.

**Comment by tjfsteele** [comment]
> Note: I plan on updating this project with the new version of IOTWebConf but this got delayed by external factors (I broke my own clock). Any contribution towards maintaining this project is most welcome :)

May be able to help - email github@tjfs.com

**Comment by t0mg** [comment]
Thanks for the PR. Happy to discuss if you're willing to help further! On my side I don't think I'll be able to work on this before end of year.

**Comment by tjfsteele** [comment]
Might be helpful if we could chat on email as opposed to github?

Thanks

Tim

**Comment by tjfsteele** [comment]
> Happy to discuss if you're willing to help further!

Hope to hear from you soon.

Tim
